#!/usr/bin/env python3
"""GRACE artifact-corpus audit — single entry point.

Usage:
    python3 run_audit.py all        run every stage fresh (slow: ~30-60 min)
    python3 run_audit.py mechsearch | dataflow | invariants | reexec | inject | phantom
    python3 run_audit.py table      build the per-run claim-accounting table
                                    (from cached stage outputs if present, else fresh)
                                    -> audit_corpus_table.txt + audit_corpus_table.tex

Stages (each also runnable standalone; see module docstrings for method specs):
    mechsearch   automated mechanism search with decoy-calibrated null rates
    dataflow     AST taint analysis: literal-only script outputs, silent skips
    invariants   physics-invariant battery (bounds, Poisson floor, batch ratio)
    reexec       differential re-execution with log-synthesized inputs
    inject       fault-injection calibration of the pipeline itself
    phantom      moment inversion + exhaustive subset exclusion (1486.17 class)

Requires the corpus at common.ROOT and: numpy pandas pyarrow matplotlib.
"""
import sys, os, re, subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
STAGES = {'mechsearch': 'mechsearch.py', 'dataflow': 'dataflow.py',
          'invariants': 'invariants.py', 'reexec': 'reexec.py',
          'inject': 'inject.py', 'phantom': 'prefix_enum.py'}
CACHE = {'mechsearch': 'mechsearch_full.txt', 'dataflow': 'dataflow_full.txt',
         'invariants': 'invariants_full.txt'}

def run_stage(name, args=()):
    out = CACHE.get(name, f'{name}_out.txt')
    print(f'== stage {name} -> {out}')
    with open(out, 'w') as f:
        subprocess.run([sys.executable, os.path.join(HERE, STAGES[name]), *args],
                       stdout=f, stderr=subprocess.STDOUT)
    return out

def ensure(name):
    p = CACHE.get(name)
    if p and os.path.exists(p): return p
    for c in (os.path.join(HERE, CACHE.get(name, '')), CACHE.get(name, '')):
        if c and os.path.exists(c): return c
    return run_stage(name)

def build_table():
    """Per-run claim accounting from mechsearch output, hardcode counts from
    dataflow, invariant flags from invariants. The paper's denominator table."""
    ms, df, iv = ensure('mechsearch'), ensure('dataflow'), ensure('invariants')
    runs = {}
    cur = None
    for ln in open(ms):
        m = re.match(r'### (\S+):', ln)
        if m: cur = m.group(1); runs.setdefault(cur, {})
        s = re.search(r'summary: (\d+) log-verified, (\d+) json-copies, (\d+) '
                      r'diagnosed-by-formula, (\d+) unexplained', ln)
        if s and cur:
            runs[cur].update(logv=int(s.group(1)), copy=int(s.group(2)),
                             diag=int(s.group(3)), unex=int(s.group(4)))
        if 'TABLE-ROW UNSOURCED' in ln and cur:
            runs[cur]['rows'] = runs[cur].get('rows', 0) + 1
        if 'CORROBORATED family' in ln and cur:
            runs[cur]['corr'] = runs[cur].get('corr', 0) + 1
    phys = re.compile(r'yield|efficien|resolut|improve|quench|signific|p_value|'
                      r'discrimin|purity|containment|linearity|uniformity', re.I)
    cur = None
    for ln in open(df):
        m = re.match(r'### (\S+)', ln)
        if m: cur = m.group(1).strip()
        if cur and ('HARDCODED' in ln or 'LIT-ONLY' in ln) and phys.search(ln):
            runs.setdefault(cur, {})['hc'] = runs[cur].get('hc', 0) + 1
        if cur and 'SILENT-SKIP' in ln:
            runs.setdefault(cur, {})['skip'] = runs[cur].get('skip', 0) + 1
    cur = None
    for ln in open(iv):
        m = re.match(r'### (\S+)', ln)
        if m: cur = m.group(1).strip()
        if cur and re.match(r'\s+I\d ', ln):
            runs.setdefault(cur, {})['inv'] = runs[cur].get('inv', 0) + 1

    cols = ['logv', 'copy', 'diag', 'unex', 'hc', 'skip', 'inv', 'rows', 'corr']
    hdr = ['run', 'log-ver', 'copies', 'diagnosed', 'unexpl', 'HC-phys',
           'skips', 'invar', 'bad-rows', 'corrob']
    lines = ['  '.join(f'{h:<10}' for h in hdr)]
    tot = dict.fromkeys(cols, 0)
    for r in sorted(runs):
        d = runs[r]
        lines.append('  '.join([f'{r:<24}'[:24].ljust(10)] +
                               [f'{d.get(c, 0):<10}' for c in cols]))
        for c in cols: tot[c] += d.get(c, 0)
    lines.append('  '.join([f'{"TOTAL":<10}'] + [f'{tot[c]:<10}' for c in cols]))
    txt = '\n'.join(lines)
    open('audit_corpus_table.txt', 'w').write(txt + '\n')
    print(txt)
    # LaTeX
    tex = ['% Auto-generated by run_audit.py table — per-run claim accounting',
           r'\begin{table*}[t]\centering\small',
           r'\caption{Corpus-wide claim accounting. Log-verified: report/JSON numbers '
           r'reproduced from per-event logs by identity; copies: verbatim inter-JSON '
           r'duplicates; diagnosed: reproduced only by a nontrivial formula passing '
           r'decoy-null calibration; unexplained: no formula in the bounded grammar '
           r'matches (includes multiplicity-rejected ambiguous matches). HC-phys: '
           r'physics-class script outputs reachable only from literal assignments '
           r'(AST taint). Skips: existence-guarded silent data omissions. Invar: '
           r'physics-invariant violations. Bad rows: report table rows with $\geq 2$ '
           r'high-precision cells and zero archive support.}',
           r'\label{tab:corpus-accounting}',
           r'\begin{tabular}{lrrrrrrrrr}\toprule',
           r'Run & Log-ver. & Copies & Diag. & Unexpl. & HC & Skips & Invar. & Rows & Corrob. \\ \midrule']
    for r in sorted(runs):
        d = runs[r]
        tex.append(r.replace('_', r'\_') + ' & ' +
                   ' & '.join(str(d.get(c, 0)) for c in cols) + r' \\')
    tex += [r'\midrule', 'Total & ' + ' & '.join(str(tot[c]) for c in cols) + r' \\',
            r'\bottomrule\end{tabular}\end{table*}']
    open('audit_corpus_table.tex', 'w').write('\n'.join(tex) + '\n')
    print('\nwrote audit_corpus_table.txt and audit_corpus_table.tex')

if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else 'table'
    if cmd == 'all':
        for s in STAGES: run_stage(s)
        build_table()
    elif cmd == 'table':
        build_table()
    elif cmd in STAGES:
        run_stage(cmd, sys.argv[2:])
    else:
        print(__doc__)
